# -*- coding: utf-8 -*-
"""Secret Message Encoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TeTX0NH2GgomhsgBVa1WuJK_4I4Zk-u
"""

def encrypt_message(message):

    # Substitution key
    encryption_key = {
        'A': '@',
        'B': '#',
        'C': '$',
        'D': '%',
        'E': '&',
        'F': '*',
        'G': '!',
        'H': '^',
        'I': '(',
        'J': ')',
        'K': '-',
        'L': '+',
        'M': '=',
        'N': '/',
        'O': '?',
        'P': '<',
        'Q': '>',
        'R': '[',
        'S': ']',
        'T': '{',
        'U': '}',
        'V': ':',
        'W': ';',
        'X': '"',
        'Y': "'",
        'Z': '#'
    }

    encrypted = ""
    for char in message.upper():
        if char in encryption_key:
            encrypted += encryption_key[char]
        else:
            encrypted += char
    return encrypted

def decrypt_message(secret_message):
    encryption_key = {
        '@':'A',
        '#':'B',
        '$':'C',
        '%':'D',
        '&':'E',
        '*':'F',
        '!':'G',
        '^':'H',
        '(':'I',
        ')':'J',
        '-':'K',
        '+':'L',
        '=':'M',
        '/':'N',
        '?':'O',
        '<':'P',
        '>':'Q',
        '[':'R',
        ']':'S',
        '{':'T',
        '}':'U',
        ':':'V',
        ';':'W',
        '"':'X',
        "'":'Y'
    }

    decrypted = ""
    for char in secret_message:
        if char in encryption_key:
            decrypted += encryption_key[char]
        else:
            decrypted += char
    return decrypted

# Main Program
print("Secret Message Encoder")
message = input("Enter your message: ")
encrypted_message = encrypt_message(message)

print("\nEncrypted Message:")
print(encrypted_message)

decrypted_message = decrypt_message(encrypted_message)

print("\nDecrypted Message:")
print(decrypted_message)